/**
 * Clone Arena — 2 clones debate each other
 * The viral "Clone vs Clone" feature
 */

import { CloneBrain, loadSoul } from '../brain/clone.js';
import { createProvider, autoDetectProvider } from '../brain/router.js';
import { loadConfig } from '../config/loader.js';
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { join } from 'path';

export class CloneArena {
    constructor(options = {}) {
        this.config = loadConfig();
        const providerName = options.provider || this.config.llm?.provider || autoDetectProvider();
        this.provider = createProvider(providerName);
        this.maxRounds = options.rounds || 5;
    }

    /**
     * Load a clone from SOUL.md
     */
    loadClone(soulPath, name) {
        const content = readFileSync(soulPath, 'utf-8');
        const brain = new CloneBrain(content, this.config);
        const nameMatch = content.match(/- Name:\s*(.+)/);
        return {
            name: name || nameMatch?.[1]?.trim() || 'Clone',
            brain,
            soulContent: content,
        };
    }

    /**
     * Run a debate between 2 clones
     */
    async runDebate(clone1, clone2, topic, callbacks = {}) {
        const transcript = [];
        let context = '';

        // Opening: clone1 starts
        const opener = await this._generateReply(
            clone1,
            `Someone asks: "${topic}" — give your opinion naturally, in your own style. Keep it short and casual.`,
            context,
        );
        transcript.push({ speaker: clone1.name, text: opener });
        context = `${clone1.name}: ${opener}`;
        callbacks.onMessage?.(clone1.name, opener, 1);

        // Alternating rounds
        for (let round = 1; round <= this.maxRounds; round++) {
            // Clone 2 responds
            const reply2 = await this._generateReply(
                clone2,
                `You're in a casual debate about "${topic}". ${clone1.name} just said: "${transcript[transcript.length - 1].text}"\n\nRespond naturally in your own style. Disagree, agree, or joke about it. Keep it short.`,
                context,
            );
            transcript.push({ speaker: clone2.name, text: reply2 });
            context += `\n${clone2.name}: ${reply2}`;
            callbacks.onMessage?.(clone2.name, reply2, round * 2);

            if (round >= this.maxRounds) break;

            // Clone 1 responds
            const reply1 = await this._generateReply(
                clone1,
                `You're in a casual debate about "${topic}". ${clone2.name} just said: "${transcript[transcript.length - 1].text}"\n\nRespond naturally in your own style. Keep it short and fun.`,
                context,
            );
            transcript.push({ speaker: clone1.name, text: reply1 });
            context += `\n${clone1.name}: ${reply1}`;
            callbacks.onMessage?.(clone1.name, reply1, round * 2 + 1);
        }

        return {
            topic,
            clone1: clone1.name,
            clone2: clone2.name,
            rounds: this.maxRounds,
            transcript,
        };
    }

    /**
     * Export transcript to markdown
     */
    exportTranscript(result, outputDir = './data') {
        if (!existsSync(outputDir)) mkdirSync(outputDir, { recursive: true });

        const id = Date.now().toString(36);
        const filename = `arena-${id}.md`;
        const filepath = join(outputDir, filename);

        let md = `# 🏟️ Clone Arena\n\n`;
        md += `**${result.clone1}** vs **${result.clone2}**\n`;
        md += `**Topic:** ${result.topic}\n`;
        md += `**Rounds:** ${result.rounds}\n\n---\n\n`;

        for (const msg of result.transcript) {
            md += `**${msg.speaker}:** ${msg.text}\n\n`;
        }

        md += `---\n*Generated by OpenSelf Clone Arena*\n`;
        writeFileSync(filepath, md, 'utf-8');
        return filepath;
    }

    async _generateReply(clone, prompt, context) {
        const systemPrompt = clone.brain.buildSystemPrompt(
            { name: 'Arena Opponent', relationship: 'debate partner', channel: 'Clone Arena' },
            context,
        );
        const reply = await this.provider.chat(systemPrompt, prompt);
        return reply.trim();
    }
}
